const NAVIGATION_ROUTES = {
  ROOT: 'ROOT',
};

const BOTTOM_TABS_ROUTES = {
  TODAY_SCREEN: 'TODAY_SCREEN',
  SURPLUS_SCREEN: 'SURPLUS_SCREEN',
  BUDGET_SCREEN: 'BUDGET_SCREEN',
  REPORT_SCREEN: 'REPORT_SCREEN',
  OTHER_SCREEN: 'OTHER_SCREEN',
};

const CONFIGS = {
  API_URL: '',
  APP_KEY: '@moneymoon',
  URL_API_NO_NEED_REFRESH: [],
};

export {CONFIGS, NAVIGATION_ROUTES, BOTTOM_TABS_ROUTES};
