/** @format */

export const NAVIGATION_ROUTES = {
  ROOT: 'ROOT',
};

export const BOTTOM_TABS_ROUTES = {
  TODAY_SCREEN: 'TODAY_SCREEN',
  SURPLUS_SCREEN: 'SURPLUS_SCREEN',
  BUDGET_SCREEN: 'BUDGET_SCREEN',
  REPORT_SCREEN: 'REPORT_SCREEN',
  OTHER_SCREEN: 'OTHER_SCREEN',
};
